#!/usr/bin/env node
/**
 * Sync LLM rule files from llm/rules/ to one selected tool target.
 * Edit the source files in llm/rules/, then run:
 *   npm run sync-llm-rules -- --target cursor
 */

import { readFile, writeFile, mkdir } from 'fs/promises'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const config = JSON.parse(await readFile(join(__dirname, 'config.json'), 'utf8'))
const defaultRules = Array.isArray(config.defaultRules) ? config.defaultRules : []
const ENABLED_TARGETS = Object.entries(config.targets)
  .filter(([, enabled]) => enabled)
  .map(([name]) => name)

function parseTargetArg(args) {
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i]
    if (arg === '--target') return args[i + 1]
    if (arg.startsWith('--target=')) return arg.slice('--target='.length)
  }
  return null
}

const target = parseTargetArg(process.argv.slice(2))

if (!target) {
  console.error(
    `Missing target. Use --target <name>. Enabled targets: ${ENABLED_TARGETS.join(', ')}`
  )
  process.exit(1)
}

if (!(target in config.targets)) {
  console.error(`Unknown target "${target}". Available targets: ${Object.keys(config.targets).join(', ')}`)
  process.exit(1)
}

if (!config.targets[target]) {
  console.error(`Target "${target}" is disabled in llm/config.json.`)
  process.exit(1)
}

const ROOT_RULE_FILE = 'root.md'
const DIRECTORY_LAYOUT_START = '<!-- sync-llm-rules:directory-layout:start -->'
const DIRECTORY_LAYOUT_END = '<!-- sync-llm-rules:directory-layout:end -->'

async function readRule(filename) {
  return readFile(join(__dirname, 'rules', filename), 'utf8')
}

async function writeRule(filename, content) {
  return writeFile(join(__dirname, 'rules', filename), content, 'utf8')
}

async function write(relPath, content) {
  const abs = join(ROOT, relPath)
  await mkdir(dirname(abs), { recursive: true })
  await writeFile(abs, content, 'utf8')
  console.log(`  ${relPath}`)
}

function banner(sources) {
  const list = Array.isArray(sources) ? sources : [sources]
  const sourceList = list.map((source) => `llm/rules/${source}`).join(', ')
  return `<!-- Generated by llm/sync.mjs from ${sourceList} — edit the source, not this file -->\n\n`
}

function cursorMdc({ description, globs, alwaysApply = false }, content) {
  const lines = ['---', `description: ${description}`]
  if (globs) lines.push(`globs: ${globs}`)
  lines.push(`alwaysApply: ${alwaysApply}`, '---', '', content)
  return lines.join('\n')
}

function buildDirectoryLayoutBlock(modules) {
  const lines = modules.map((mod) => `- \`${mod.path}/\` — ${mod.description}`)
  return [
    '## Directory layout',
    '',
    DIRECTORY_LAYOUT_START,
    ...lines,
    DIRECTORY_LAYOUT_END,
    '',
  ].join('\n')
}

function upsertDirectoryLayoutSection(rootContent, modules) {
  const generated = buildDirectoryLayoutBlock(modules)
  const heading = '## Directory layout'

  if (rootContent.includes(heading)) {
    const start = rootContent.indexOf(heading)
    const nextHeadingIndex = rootContent.indexOf('\n## ', start + heading.length)
    const end = nextHeadingIndex === -1 ? rootContent.length : nextHeadingIndex + 1
    return `${rootContent.slice(0, start)}${generated.trimEnd()}\n${rootContent.slice(end)}`
  }

  // If missing entirely, append a new section at the end.
  const withNewline = rootContent.endsWith('\n') ? rootContent : `${rootContent}\n`
  return `${withNewline}\n${generated}`
}

// ── Root-level rules ──────────────────────────────────────────────────────────

let root = await readRule(ROOT_RULE_FILE)
const updatedRoot = upsertDirectoryLayoutSection(root, config.modules)
if (updatedRoot !== root) {
  await writeRule(ROOT_RULE_FILE, updatedRoot)
  root = updatedRoot
  console.log(`Updated llm/rules/${ROOT_RULE_FILE} directory layout from llm/config.json`)
}

const defaultRuleContents = await Promise.all(defaultRules.map((rule) => readRule(rule)))
const rootContent = [root, ...defaultRuleContents].join('\n\n')

console.log(`Target: ${target}`)
console.log('Root rules:')
if (target === 'claudeCode') await write('CLAUDE.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
if (target === 'codex') await write('AGENTS.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
if (target === 'copilot') await write('.github/copilot-instructions.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
if (target === 'windsurf') await write('.windsurfrules', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
if (target === 'cline') await write('.clinerules', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
if (target === 'cursor') {
  await write(
    '.cursor/rules/root.mdc',
    cursorMdc({ description: 'Project-wide rules', alwaysApply: true }, rootContent)
  )
}

// ── Module-level rules ────────────────────────────────────────────────────────

if (target === 'claudeCode' || target === 'cursor') {
  console.log('\nModule rules:')
  for (const mod of config.modules) {
    const content = await readRule(mod.rule)
    const name = basename(mod.rule, '.md')

    if (target === 'claudeCode') {
      await write(`${mod.path}/CLAUDE.md`, banner(mod.rule) + content)
    }
    if (target === 'cursor') {
      await write(
        `.cursor/rules/${name}.mdc`,
        cursorMdc({ description: mod.description, globs: `${mod.path}/**`, alwaysApply: false }, content)
      )
    }
  }
}

console.log('\nDone.')
