#!/usr/bin/env node
/**
 * Sync LLM rule files from llm/rules/ to tool-specific outputs.
 *
 * Usage:
 *   node llm/sync.mjs              # auto-detect installed tools, generate all
 *   node llm/sync.mjs --all        # same as above
 *   node llm/sync.mjs --target cursor   # single target (manual override)
 *
 * Target values in llm/config.json:
 *   "auto"  — detect at runtime (check PATH + tool-specific directories)
 *   true    — always generate
 *   false   — never generate
 */

import { readFile, writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'
import { execFileSync } from 'child_process'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const config = JSON.parse(await readFile(join(__dirname, 'config.json'), 'utf8'))
const defaultRules = Array.isArray(config.defaultRules) ? config.defaultRules : []

// ── Tool detection ────────────────────────────────────────────────────────────

function which(bin) {
  try {
    execFileSync('which', [bin], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

const DETECTORS = {
  claudeCode: () => which('claude'),
  cursor:     () => existsSync(join(ROOT, '.cursor')) || which('cursor'),
  copilot:    () => existsSync(join(ROOT, '.github')),
  windsurf:   () => which('windsurf'),
  cline:      () => which('cline'),
  codex:      () => which('codex'),
}

function resolveTarget(name, value) {
  if (value === false) return false
  if (value === true) return true
  if (value === 'auto') {
    const detect = DETECTORS[name]
    return detect ? detect() : false
  }
  return false
}

// ── Argument parsing ──────────────────────────────────────────────────────────

function parseArgs(args) {
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    if (arg === '--target') return { mode: 'single', target: args[i + 1] }
    if (arg.startsWith('--target=')) return { mode: 'single', target: arg.slice('--target='.length) }
    if (arg === '--all') return { mode: 'all' }
  }
  return { mode: 'all' }
}

const { mode, target: singleTarget } = parseArgs(process.argv.slice(2))

let resolvedTargets

if (mode === 'single') {
  if (!singleTarget) {
    console.error('Missing target name. Use --target <name>.')
    process.exit(1)
  }
  if (!(singleTarget in config.targets)) {
    console.error(`Unknown target "${singleTarget}". Available: ${Object.keys(config.targets).join(', ')}`)
    process.exit(1)
  }
  resolvedTargets = [singleTarget]
} else {
  resolvedTargets = Object.entries(config.targets)
    .filter(([name, value]) => resolveTarget(name, value))
    .map(([name]) => name)

  if (resolvedTargets.length === 0) {
    console.log('No tools detected. Run with --target <name> to generate manually.')
    console.log(`Available targets: ${Object.keys(config.targets).join(', ')}`)
    process.exit(0)
  }

  console.log(`Detected targets: ${resolvedTargets.join(', ')}`)
}

// ── File helpers ──────────────────────────────────────────────────────────────

const ROOT_RULE_FILE = 'root.md'
const DIRECTORY_LAYOUT_START = '<!-- sync-llm-rules:directory-layout:start -->'
const DIRECTORY_LAYOUT_END = '<!-- sync-llm-rules:directory-layout:end -->'

async function readRule(filename) {
  return readFile(join(__dirname, 'rules', filename), 'utf8')
}

async function writeRule(filename, content) {
  return writeFile(join(__dirname, 'rules', filename), content, 'utf8')
}

async function write(relPath, content) {
  const abs = join(ROOT, relPath)
  await mkdir(dirname(abs), { recursive: true })
  await writeFile(abs, content, 'utf8')
  console.log(`  ${relPath}`)
}

function banner(sources) {
  const list = Array.isArray(sources) ? sources : [sources]
  const sourceList = list.map((s) => `llm/rules/${s}`).join(', ')
  return `<!-- Generated by llm/sync.mjs from ${sourceList} — edit the source, not this file -->\n\n`
}

function cursorMdc({ description, globs, alwaysApply = false }, content) {
  const lines = ['---', `description: ${description}`]
  if (globs) lines.push(`globs: ${globs}`)
  lines.push(`alwaysApply: ${alwaysApply}`, '---', '', content)
  return lines.join('\n')
}

function buildDirectoryLayoutBlock(modules) {
  const lines = modules.map((mod) => `- \`${mod.path}/\` — ${mod.description}`)
  return [
    '## Directory layout',
    '',
    DIRECTORY_LAYOUT_START,
    ...lines,
    DIRECTORY_LAYOUT_END,
    '',
  ].join('\n')
}

function upsertDirectoryLayoutSection(rootContent, modules) {
  const generated = buildDirectoryLayoutBlock(modules)
  const heading = '## Directory layout'

  if (rootContent.includes(heading)) {
    const start = rootContent.indexOf(heading)
    const nextHeadingIndex = rootContent.indexOf('\n## ', start + heading.length)
    const end = nextHeadingIndex === -1 ? rootContent.length : nextHeadingIndex + 1
    return `${rootContent.slice(0, start)}${generated.trimEnd()}\n${rootContent.slice(end)}`
  }

  const withNewline = rootContent.endsWith('\n') ? rootContent : `${rootContent}\n`
  return `${withNewline}\n${generated}`
}

// ── Update root rule directory layout ────────────────────────────────────────

let root = await readRule(ROOT_RULE_FILE)
const updatedRoot = upsertDirectoryLayoutSection(root, config.modules)
if (updatedRoot !== root) {
  await writeRule(ROOT_RULE_FILE, updatedRoot)
  root = updatedRoot
  console.log(`Updated llm/rules/${ROOT_RULE_FILE} directory layout from llm/config.json`)
}

const defaultRuleContents = await Promise.all(defaultRules.map((rule) => readRule(rule)))
const rootContent = [root, ...defaultRuleContents].join('\n\n')

// ── Generate per target ───────────────────────────────────────────────────────

for (const t of resolvedTargets) {
  console.log(`\nTarget: ${t}`)
  console.log('Root rules:')

  if (t === 'claudeCode') await write('CLAUDE.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
  if (t === 'codex')      await write('AGENTS.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
  if (t === 'copilot')    await write('.github/copilot-instructions.md', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
  if (t === 'windsurf')   await write('.windsurfrules', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
  if (t === 'cline')      await write('.clinerules', banner([ROOT_RULE_FILE, ...defaultRules]) + rootContent)
  if (t === 'cursor') {
    await write(
      '.cursor/rules/root.mdc',
      cursorMdc({ description: 'Project-wide rules', alwaysApply: true }, rootContent)
    )
  }

  if (t === 'claudeCode' || t === 'cursor') {
    console.log('Module rules:')
    for (const mod of config.modules) {
      const content = await readRule(mod.rule)
      const name = basename(mod.rule, '.md')

      if (t === 'claudeCode') {
        await write(`${mod.path}/CLAUDE.md`, banner(mod.rule) + content)
      }
      if (t === 'cursor') {
        await write(
          `.cursor/rules/${name}.mdc`,
          cursorMdc({ description: mod.description, globs: `${mod.path}/**`, alwaysApply: false }, content)
        )
      }
    }
  }
}

console.log('\nDone.')
