#!/usr/bin/env node
/**
 * Sync LLM rule files from llm/rules/ to one selected tool target.
 * Edit the source files in llm/rules/, then run:
 *   npm run sync-cursor-rules
 * or:
 *   npm run sync-llm-rules -- --target cursor
 */

import { readFile, writeFile, mkdir } from 'fs/promises'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const config = JSON.parse(await readFile(join(__dirname, 'config.json'), 'utf8'))
const ENABLED_TARGETS = Object.entries(config.targets)
  .filter(([, enabled]) => enabled)
  .map(([name]) => name)

function parseTargetArg(args) {
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i]
    if (arg === '--target') return args[i + 1]
    if (arg.startsWith('--target=')) return arg.slice('--target='.length)
  }
  return null
}

const target = parseTargetArg(process.argv.slice(2))

if (!target) {
  console.error(
    `Missing target. Use --target <name>. Enabled targets: ${ENABLED_TARGETS.join(', ')}`
  )
  process.exit(1)
}

if (!(target in config.targets)) {
  console.error(`Unknown target "${target}". Available targets: ${Object.keys(config.targets).join(', ')}`)
  process.exit(1)
}

if (!config.targets[target]) {
  console.error(`Target "${target}" is disabled in llm/config.json.`)
  process.exit(1)
}

async function readRule(filename) {
  return readFile(join(__dirname, 'rules', filename), 'utf8')
}

async function write(relPath, content) {
  const abs = join(ROOT, relPath)
  await mkdir(dirname(abs), { recursive: true })
  await writeFile(abs, content, 'utf8')
  console.log(`  ${relPath}`)
}

function banner(source) {
  return `<!-- Generated by llm/sync.mjs from llm/rules/${source} — edit the source, not this file -->\n\n`
}

function cursorMdc({ description, globs, alwaysApply = false }, content) {
  const lines = ['---', `description: ${description}`]
  if (globs) lines.push(`globs: ${globs}`)
  lines.push(`alwaysApply: ${alwaysApply}`, '---', '', content)
  return lines.join('\n')
}

// ── Root-level rules ──────────────────────────────────────────────────────────

const root = await readRule('root.md')

console.log(`Target: ${target}`)
console.log('Root rules:')
if (target === 'claudeCode') await write('CLAUDE.md', banner('root.md') + root)
if (target === 'codex') await write('AGENTS.md', banner('root.md') + root)
if (target === 'copilot') await write('.github/copilot-instructions.md', banner('root.md') + root)
if (target === 'windsurf') await write('.windsurfrules', banner('root.md') + root)
if (target === 'cline') await write('.clinerules', banner('root.md') + root)
if (target === 'cursor') {
  await write(
    '.cursor/rules/root.mdc',
    cursorMdc({ description: 'Project-wide rules', alwaysApply: true }, root)
  )
}

// ── Module-level rules ────────────────────────────────────────────────────────

if (target === 'claudeCode' || target === 'cursor') {
  console.log('\nModule rules:')
  for (const mod of config.modules) {
    const content = await readRule(mod.rule)
    const name = basename(mod.rule, '.md')

    if (target === 'claudeCode') {
      await write(`${mod.path}/CLAUDE.md`, banner(mod.rule) + content)
    }
    if (target === 'cursor') {
      await write(
        `.cursor/rules/${name}.mdc`,
        cursorMdc({ description: mod.description, globs: `${mod.path}/**`, alwaysApply: false }, content)
      )
    }
  }
}

console.log('\nDone.')
